### ISSUE TITLE
好像不支持webp？

### ISSUE THREAD

**Issue by mrxiaozuo** [SDWebImage/SDWebImageYYPlugin#3]
通过CocoaPods导入了pod 'SDWebImageYYPlugin'
然后设置了解码器
[SDImageCodersManager.sharedManager addCoder:SDImageYYCoder.sharedCoder];
加载本地图片
YYAnimatedImageView *imageView;
imageView.image=[YYImage imageNamed:@"xxx.webp"];
加载网络图片
[imageView sd_setImageWithURL:[NSURL URLWithString:@"http://www.xxx.com/xx/xx/image.webp"]];

都无法加载成功

**Comment by dreampiggy** [comment]
Our demo can successfully render WebP (including animated WebP) images.

![image](https://user-images.githubusercontent.com/6919743/65655618-6c912300-e04f-11e9-9acf-bed322464bf1.png)


You should change your Podfile to include YYImage with webp support.

```ruby
pod 'SDWebImageYYPlugin/YYImage'
pod 'YYImage/libwebp'
```

See [YYImage](https://github.com/ibireme/YYImage) readme here. But I remember the YYImage is not long maintained, and the latest commit is not released. You may need to use the branch or commit dependency for it. Like

```ruby
pod 'YYImage/libwebp', :git => 'https://github.com/ibireme/YYImage.git', :branch => 'master'
```
