### ISSUE TITLE
build eror on Xcode 12

### ISSUE THREAD

**Issue by voshk** [SDWebImage/SDWebImageYYPlugin#7]
build error on Xcode 12.

YYCache+SDAdditions.m

[self.diskCache objectForKey:key withBlock:^(NSString * _Nonnull key, id<NSObject, NSCoding> _Nullable object) {

: Incompatible block pointer types sending 'void (^)(NSString * _Nonnull __strong, id<NSObject,NSCoding>  _Nullable __strong)' to parameter of type 'void (^ _Nonnull)(NSString * _Nonnull __strong, id<NSCoding>  _Nullable __strong)'

**Comment by dreampiggy** [comment]
Effected by Xcode 12's clang update:

![image](https://user-images.githubusercontent.com/6919743/93555165-c947c500-f9a7-11ea-8da2-ca3c84ee22c0.png)

Fix avaialble later.

**Comment by voshk** [comment]
> Effected by Xcode 12's clang update:
> 
> ![image](https://user-images.githubusercontent.com/6919743/93555165-c947c500-f9a7-11ea-8da2-ca3c84ee22c0.png)
> 
> Fix avaialble later.

ok.thanks

**Comment by dreampiggy** [comment]
@voshk Please upgrade to use [SDWebImageYYPlugin v0.6.0](https://github.com/SDWebImage/SDWebImageYYPlugin/releases/tag/0.6.0) version...

**Comment by voshk** [comment]
> @voshk Please upgrade to use [SDWebImageYYPlugin v0.6.0](https://github.com/SDWebImage/SDWebImageYYPlugin/releases/tag/0.6.0) version...

Got it!
